//go:build darwin

// ***** DO NOT EDIT. *****
// Code generated by the
// github.com/aileron-projects/go-sockopts/cmd/generator/generate.go
package sockopts

import "golang.org/x/sys/unix"

var (
	SO_DEBUG      = Bool{Level: unix.SOL_SOCKET, Opt: unix.SO_DEBUG, Name: "SO_DEBUG"}
	SO_KEEPALIVE  = Bool{Level: unix.SOL_SOCKET, Opt: unix.SO_KEEPALIVE, Name: "SO_KEEPALIVE"}
	SO_LINGER     = Linger{Level: unix.SOL_SOCKET, Opt: unix.SO_LINGER, Name: "SO_LINGER"}
	SO_RCVBUF     = Int{Level: unix.SOL_SOCKET, Opt: unix.SO_RCVBUF, Name: "SO_RCVBUF"}
	SO_SNDBUF     = Int{Level: unix.SOL_SOCKET, Opt: unix.SO_SNDBUF, Name: "SO_SNDBUF"}
	SO_SNDTIMEO   = Timeval{Level: unix.SOL_SOCKET, Opt: unix.SO_SNDTIMEO, Name: "SO_SNDTIMEO"}
	SO_RCVTIMEO   = Timeval{Level: unix.SOL_SOCKET, Opt: unix.SO_RCVTIMEO, Name: "SO_RCVTIMEO"}
	SO_REUSEADDR  = Bool{Level: unix.SOL_SOCKET, Opt: unix.SO_REUSEADDR, Name: "SO_REUSEADDR"}
	SO_REUSEPORT  = Bool{Level: unix.SOL_SOCKET, Opt: unix.SO_REUSEPORT, Name: "SO_REUSEPORT"}
	IP_TTL        = Int{Level: unix.IPPROTO_IP, Opt: unix.IP_TTL, Name: "IP_TTL"}
	IPV6_V6ONLY   = Bool{Level: unix.IPPROTO_IPV6, Opt: unix.IPV6_V6ONLY, Name: "IPV6_V6ONLY"}
	TCP_KEEPCNT   = Int{Level: unix.IPPROTO_TCP, Opt: unix.TCP_KEEPCNT, Name: "TCP_KEEPCNT"}
	TCP_KEEPINTVL = Int{Level: unix.IPPROTO_TCP, Opt: unix.TCP_KEEPINTVL, Name: "TCP_KEEPINTVL"}
	TCP_MAXSEG    = Int{Level: unix.IPPROTO_TCP, Opt: unix.TCP_MAXSEG, Name: "TCP_MAXSEG"}
	TCP_NODELAY   = Bool{Level: unix.IPPROTO_TCP, Opt: unix.TCP_NODELAY, Name: "TCP_NODELAY"}
	TCP_FASTOPEN  = Bool{Level: unix.IPPROTO_TCP, Opt: unix.TCP_FASTOPEN, Name: "TCP_FASTOPEN"}
)
