//go:build linux

// ***** DO NOT EDIT. *****
// Code generated by the
// github.com/aileron-projects/go-sockopts/cmd/generator/generate.go
package sockopts

import "golang.org/x/sys/unix"

var (
	SO_BINDTOIFINDEX        = Int{Level: unix.SOL_SOCKET, Opt: unix.SO_BINDTOIFINDEX, Name: "SO_BINDTOIFINDEX"}
	SO_BINDTODEVICE         = String{Level: unix.SOL_SOCKET, Opt: unix.SO_BINDTODEVICE, Name: "SO_BINDTODEVICE"}
	SO_DEBUG                = Bool{Level: unix.SOL_SOCKET, Opt: unix.SO_DEBUG, Name: "SO_DEBUG"}
	SO_KEEPALIVE            = Bool{Level: unix.SOL_SOCKET, Opt: unix.SO_KEEPALIVE, Name: "SO_KEEPALIVE"}
	SO_LINGER               = Linger{Level: unix.SOL_SOCKET, Opt: unix.SO_LINGER, Name: "SO_LINGER"}
	SO_MARK                 = Int{Level: unix.SOL_SOCKET, Opt: unix.SO_MARK, Name: "SO_MARK"}
	SO_RCVBUF               = Int{Level: unix.SOL_SOCKET, Opt: unix.SO_RCVBUF, Name: "SO_RCVBUF"}
	SO_RCVBUFFORCE          = Int{Level: unix.SOL_SOCKET, Opt: unix.SO_RCVBUFFORCE, Name: "SO_RCVBUFFORCE"}
	SO_SNDBUF               = Int{Level: unix.SOL_SOCKET, Opt: unix.SO_SNDBUF, Name: "SO_SNDBUF"}
	SO_SNDBUFFORCE          = Int{Level: unix.SOL_SOCKET, Opt: unix.SO_SNDBUFFORCE, Name: "SO_SNDBUFFORCE"}
	SO_SNDTIMEO             = Timeval{Level: unix.SOL_SOCKET, Opt: unix.SO_SNDTIMEO, Name: "SO_SNDTIMEO"}
	SO_RCVTIMEO             = Timeval{Level: unix.SOL_SOCKET, Opt: unix.SO_RCVTIMEO, Name: "SO_RCVTIMEO"}
	SO_REUSEADDR            = Bool{Level: unix.SOL_SOCKET, Opt: unix.SO_REUSEADDR, Name: "SO_REUSEADDR"}
	SO_REUSEPORT            = Bool{Level: unix.SOL_SOCKET, Opt: unix.SO_REUSEPORT, Name: "SO_REUSEPORT"}
	IP_BIND_ADDRESS_NO_PORT = Bool{Level: unix.IPPROTO_IP, Opt: unix.IP_BIND_ADDRESS_NO_PORT, Name: "IP_BIND_ADDRESS_NO_PORT"}
	IP_FREEBIND             = Bool{Level: unix.IPPROTO_IP, Opt: unix.IP_FREEBIND, Name: "IP_FREEBIND"}
	IP_LOCAL_PORT_RANGE     = Int{Level: unix.IPPROTO_IP, Opt: unix.IP_LOCAL_PORT_RANGE, Name: "IP_LOCAL_PORT_RANGE"}
	IP_TRANSPARENT          = Bool{Level: unix.IPPROTO_IP, Opt: unix.IP_TRANSPARENT, Name: "IP_TRANSPARENT"}
	IP_TTL                  = Int{Level: unix.IPPROTO_IP, Opt: unix.IP_TTL, Name: "IP_TTL"}
	IPV6_V6ONLY             = Bool{Level: unix.IPPROTO_IPV6, Opt: unix.IPV6_V6ONLY, Name: "IPV6_V6ONLY"}
	TCP_CORK                = Bool{Level: unix.IPPROTO_TCP, Opt: unix.TCP_CORK, Name: "TCP_CORK"}
	TCP_DEFER_ACCEPT        = Int{Level: unix.IPPROTO_TCP, Opt: unix.TCP_DEFER_ACCEPT, Name: "TCP_DEFER_ACCEPT"}
	TCP_KEEPCNT             = Int{Level: unix.IPPROTO_TCP, Opt: unix.TCP_KEEPCNT, Name: "TCP_KEEPCNT"}
	TCP_KEEPIDLE            = Int{Level: unix.IPPROTO_TCP, Opt: unix.TCP_KEEPIDLE, Name: "TCP_KEEPIDLE"}
	TCP_KEEPINTVL           = Int{Level: unix.IPPROTO_TCP, Opt: unix.TCP_KEEPINTVL, Name: "TCP_KEEPINTVL"}
	TCP_LINGER2             = Linger{Level: unix.IPPROTO_TCP, Opt: unix.TCP_LINGER2, Name: "TCP_LINGER2"}
	TCP_MAXSEG              = Int{Level: unix.IPPROTO_TCP, Opt: unix.TCP_MAXSEG, Name: "TCP_MAXSEG"}
	TCP_NODELAY             = Bool{Level: unix.IPPROTO_TCP, Opt: unix.TCP_NODELAY, Name: "TCP_NODELAY"}
	TCP_QUICKACK            = Bool{Level: unix.IPPROTO_TCP, Opt: unix.TCP_QUICKACK, Name: "TCP_QUICKACK"}
	TCP_SYNCNT              = Int{Level: unix.IPPROTO_TCP, Opt: unix.TCP_SYNCNT, Name: "TCP_SYNCNT"}
	TCP_USER_TIMEOUT        = Int{Level: unix.IPPROTO_TCP, Opt: unix.TCP_USER_TIMEOUT, Name: "TCP_USER_TIMEOUT"}
	TCP_WINDOW_CLAMP        = Int{Level: unix.IPPROTO_TCP, Opt: unix.TCP_WINDOW_CLAMP, Name: "TCP_WINDOW_CLAMP"}
	TCP_FASTOPEN            = Bool{Level: unix.IPPROTO_TCP, Opt: unix.TCP_FASTOPEN, Name: "TCP_FASTOPEN"}
	TCP_FASTOPEN_CONNECT    = Bool{Level: unix.IPPROTO_TCP, Opt: unix.TCP_FASTOPEN_CONNECT, Name: "TCP_FASTOPEN_CONNECT"}
	UDP_CORK                = Bool{Level: unix.IPPROTO_UDP, Opt: unix.UDP_CORK, Name: "UDP_CORK"}
	UDP_SEGMENT             = Int{Level: unix.IPPROTO_UDP, Opt: unix.UDP_SEGMENT, Name: "UDP_SEGMENT"}
	UDP_GRO                 = Bool{Level: unix.IPPROTO_UDP, Opt: unix.UDP_GRO, Name: "UDP_GRO"}
)
