//go:build windows

// ***** DO NOT EDIT. *****
// Code generated by the
// github.com/aileron-projects/go-sockopts/cmd/generator/generate.go
package sockopts

import "golang.org/x/sys/windows"

var (
	SO_KEEPALIVE = Bool{Level: windows.SOL_SOCKET, Opt: windows.SO_KEEPALIVE, Name: "SO_KEEPALIVE"}
	SO_LINGER    = Linger{Level: windows.SOL_SOCKET, Opt: windows.SO_LINGER, Name: "SO_LINGER"}
	SO_RCVBUF    = Int{Level: windows.SOL_SOCKET, Opt: windows.SO_RCVBUF, Name: "SO_RCVBUF"}
	SO_SNDBUF    = Int{Level: windows.SOL_SOCKET, Opt: windows.SO_SNDBUF, Name: "SO_SNDBUF"}
	SO_REUSEADDR = Bool{Level: windows.SOL_SOCKET, Opt: windows.SO_REUSEADDR, Name: "SO_REUSEADDR"}
	IP_TTL       = Int{Level: windows.IPPROTO_IP, Opt: windows.IP_TTL, Name: "IP_TTL"}
	TCP_NODELAY  = Bool{Level: windows.IPPROTO_TCP, Opt: windows.TCP_NODELAY, Name: "TCP_NODELAY"}
)
