package main

import (
	"bytes"
	"os"
	"text/template"
)

const doNotEdit = `
// ***** DO NOT EDIT. *****
// Code generated by the
// github.com/aileron-projects/go-sockopts/cmd/generator/generate.go
`

func main() {
	generateLinux()
	generateWindows()
	generateDarwin()
}

func generateLinux() {
	header := "//go:build linux\n\n" + doNotEdit + "package sockopts\n\n" + "import \"golang.org/x/sys/unix\"\n\n"
	tplStr := `{{.Option}} = {{.Type}}{Level: unix.{{.Level}}, Opt: unix.{{.Option}}, Name: "{{.Option}}"}`
	tpl, _ := template.New("").Parse(tplStr + "\n")

	buf := bytes.NewBuffer([]byte(header))
	buf.WriteString("var (\n")
	for _, v := range listLinux {
		if err := tpl.Execute(buf, v); err != nil {
			panic(err)
		}
	}
	buf.WriteString(")\n")
	err := os.WriteFile("../../options_linux.go", buf.Bytes(), os.ModePerm)
	if err != nil {
		panic(err)
	}
}

func generateDarwin() {
	header := "//go:build darwin\n\n" + doNotEdit + "package sockopts\n\n" + "import \"golang.org/x/sys/unix\"\n\n"
	tplStr := `{{.Option}} = {{.Type}}{Level: unix.{{.Level}}, Opt: unix.{{.Option}}, Name: "{{.Option}}"}`
	tpl, _ := template.New("").Parse(tplStr + "\n")

	buf := bytes.NewBuffer([]byte(header))
	buf.WriteString("var (\n")
	for _, v := range listDarwin {
		if err := tpl.Execute(buf, v); err != nil {
			panic(err)
		}
	}
	buf.WriteString(")\n")
	err := os.WriteFile("../../options_darwin.go", buf.Bytes(), os.ModePerm)
	if err != nil {
		panic(err)
	}
}

func generateWindows() {
	header := "//go:build windows\n\n" + doNotEdit + "package sockopts\n\n" + "import \"golang.org/x/sys/windows\"\n\n"
	tplStr := `{{.Option}} = {{.Type}}{Level: windows.{{.Level}}, Opt: windows.{{.Option}}, Name: "{{.Option}}"}`
	tpl, _ := template.New("").Parse(tplStr + "\n")

	buf := bytes.NewBuffer([]byte(header))
	buf.WriteString("var (\n")
	for _, v := range listWindows {
		if err := tpl.Execute(buf, v); err != nil {
			panic(err)
		}
	}
	buf.WriteString(")\n")
	err := os.WriteFile("../../options_windows.go", buf.Bytes(), os.ModePerm)
	if err != nil {
		panic(err)
	}
}
